#!/bin/bash -e

if [[ ! -d ~/.dotfiles ]]; then
  git clone --recursive git@github.com:neronmoon/dotfiles.git ~/.dotfiles
  sudo apt-get -y install git mc zsh htop vim
  sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
fi
ln -sf ~/.dotfiles/.[!.]* ~/
